name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run the tests
        run: pipenv run test

  Build:
    needs: Test
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      id-token: write
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::278239571658:role/github-to-aws-oidc

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_REPO_BACKEND }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image-uri=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::278239571658:role/github-to-aws-oidc
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Print IMAGE_URI
        run: echo "IMAGE_URI=${{ needs.Build.outputs.image-uri }}"
      - name: Debug Kustomize Output
        run: |
          kustomize build > output.yaml
          cat output.yaml
      - name: Deploy Kubernetes manifests
        env:
          IMAGE_URI: ${{ needs.Build.outputs.image-uri }}
          CLUSTER: ${{ secrets.AWS_CLUSTER }}
          REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd k8s
          aws eks update-kubeconfig --name $CLUSTER --region $REGION
          kustomize edit set image backend=$IMAGE_URI
          kustomize build | kubectl apply -f -
